controllers:
    resource: ../src/Controller/
    type: attribute
app_logout:
    path: /logout
    methods: GET
    
home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login
    
register:
    path: /register
    controller: App\Controller\RegistrationController::register

    
app_first:
    path: /
    controller: App\Controller\HomeController::index


logout:
    path: /logout
    controller: App\Controller\SecurityController::logout